### PR TITLE
Tweaked imported libraries.

### PR DESCRIPTION
**Pull request by jfdona23**
Hi @rsc1975 ,

I've replaced *time* with *utime* since micro libraries are more hardware oriented and therefore they are a little more efficient.
Also, to save memory I've imported the needed functions rather than the entire module. Also adjusted the code to fit with that.

Related info about *utime*: https://docs.micropython.org/en/latest/library/utime.html

Regards.

**PS:** thanks for this library, it's pretty useful ;)

### CODE REVIEW

**Comment by Jeremy996** [comment]
Hi, I Have a measurement error, in cm the measurement is 0.3436426 and when i put the sensor in mm the measurement is 0, how can i solve this? I would appreciate your help

**Comment by jfdona23** [comment]
Hi Jeremy, I'm not the official maintainer of this lib, so you might want to try the lib in the master branch. Nevertheless, both should work.

In the lib, in the distance_mm method, try replacing:
`mm = pulse_time * 100 // 582`
By:
`mm = (pulse_time // 2) // 2.91`

Otherwise you can just convert, inside your code, your cms result into mm. (you might prefer this options)

 Cheers
Juan

**Comment by Jeremy996** [comment]
> Hi Jeremy, I'm not the official maintainer of this lib, so you might want to try the lib in the master branch. Nevertheless, both should work.
> 
> In the lib, in the distance_mm method, try replacing:
> `mm = pulse_time * 100 // 582`
> By:
> `mm = (pulse_time // 2) // 2.91`
> 
> Otherwise you can just convert, inside your code, your cms result into mm. (you might prefer this options)
> 
> Cheers
> Juan

Thank you it's working very good now

**Comment by rsc1975** [comment]
Accepted and merged manually

**Pull request closed without merging**
